on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  apiTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build and run Web API
        run: |
          cd api
          dotnet run & echo "API_PID=$!" >> $GITHUB_ENV
        env:
          pgconn: ${{secrets.PGCONN}}

      - name: Run API tests
        run: |
          cd tests
          sleep 60
          dotnet test
        env:
          pgconn: ${{secrets.PGCONN}}

      - name: Shutdown API
        run: kill $API_PID
